### ISSUE TITLE
How can used this plugin with a line chart?

### ISSUE THREAD

**Issue by ghost** [virtualstaticvoid/highcharts_trendline#2]
If the chart code is as follows:

 chart3 = new Highcharts.Chart({
            chart: {
            renderTo: 'chartdiv'
            },
        title: {
            text: 'Test Chart'
               },
         xAxis: {
        categories: ['9 Aug', '10 Aug', '11 Aug', '12 Aug', '13 Aug', '14 Aug','15 Aug']
               },
        yAxis: {
        title: {
        min:10,
            text: null
            },
    plotLines: [{
        value: 0,
        width: 1,
        color: '#808080'
            }]
                 },
    tooltip: {
    formatter: function() {
    return '<b>'+ this.series.name +'</b><br/>'+this.x +': '+ this.y;
                             }
            },
    legend: {
    layout: 'vertical',
    align: 'right',
    verticalAlign: 'top',
    x: -10,
        y: 100,
         borderWidth: 0
        },
    series: [{
        name: 'Series 1',
        type: 'line',
        data: [98,115,117,104,117,102,105]
        }]
    });

How do you the insert the trend line? I tried a few things and none of them worked. ANy help would be appreciated.

**Comment by virtualstaticvoid** [comment]
The regression calculation needs an `x` and `y` value. Since this is a linear plot, the `x` value is implied, and is the index into the array, thus you'll need to create a 2 dimensional array, where `x` is the index and `y` is the value from your source array and pass it to the `fitData` function. Then extract the `y` values from the fitted data to plot it.

You could do this with the following function:

``` javascript
function fitOneDimensionalData(source_data) {
  var trend_source_data = [];
  for(var i = source_data.length; i-->0;) {
    trend_source_data[i] = [i, source_data[i]]
  }
  var regression_data = fitData(trend_source_data).data
  var trend_line_data = [];
  for(var i = regression_data.length; i-->0;) {
    trend_line_data[i] = regression_data[i][1];
  }
  return trend_line_data;
}
```

I created a [jsFiddle](http://jsfiddle.net/rqLSk/) to illustrate.

**Comment by ghost** [comment]
Hey thanks for the quick response and I really appreciate the jsFiddle that you have created to illustrate the solution. Thanks a lot.

**Comment by virtualstaticvoid** [comment]
Cheers. I've added a 3rd demo to the repository for this example too.
