### ISSUE TITLE
Rechtschreibfehler

### ISSUE THREAD

**Issue by nicomuc** [virtualstaticvoid/highcharts_trendline#3]
"Dieser Ausweismedien sind dem Kunden zugeordnet:" - da ist ein r zuviel

 " Deakvtieren eines Gerätes führt zu unwiderruflichem Verlust der Kraft / Servo Einstellungen" -> " Deakvtieren eines Gerätes führt zu unwiderruflichem Verlust der Kraft-/Servo-Einstellungen"

**Comment by virtualstaticvoid** [comment]
Sorry I don't understand the issue.
