### ISSUE TITLE
Use regression line for projection

### ISSUE THREAD

**Issue by joedborg** [virtualstaticvoid/highcharts_trendline#5]
Is there a way to carry the line on, after the final value, for projection?

**Comment by vigneshwaranr** [comment]
I second this

**Comment by cstefano** [comment]
The calculation of the trend line (regression) data points is independent to HighCharts, so you can extrapolate the projected value mathematically, using the `slope` and `y-intercept` that is calculated by the `fitData` function.

For linear regressions the formula is `y = mx + c`. Where m = slope and c = y-intercept, so given an `x` value, you can calculate the `y` value.

**Comment by virtualstaticvoid** [comment]
I've built in support for calculating projected `x` or `y` values to the regression. See [demo5.html](https://github.com/virtualstaticvoid/highcharts_trendline/blob/master/demo5.html) for an example. 

E.g.

``` javascript
// define data array
var sourceData = [
  [106.4, 271.8],
  [295.6, 432.3],
  [129.9, 133.2],
  [144.0, 134.7],
  [216.4, 319.2],
  [435.6, 665.3]
];

var linRegression = fitData(sourceData);

// project starting and ending values
var projectedX = linRegression.x(50);
var projectedY = linRegression.x(500);

// insert projected values into the array
var linRegressionData = linRegression.data;
linRegressionData.unshift([projectedX, 50]);
linRegressionData.push([500, projectedY]);

// use linRegressionData for the data for the trend line on the chart 
...
```
