### ISSUE TITLE
If there are many records,will it display correctly?(more than 1w records)

### ISSUE THREAD

**Issue by xautjzd** [virtualstaticvoid/highcharts_trendline#7]
If there are more than 10,000 records,will it display correctly?

**Comment by virtualstaticvoid** [comment]
Highcharts is capable of handling large datasets, checkout the section on [Working with Data](http://www.highcharts.com/docs/working-with-data) in the documentation.

The trendline is pre-processed on the data, and therefore has nothing to do with Highcharts. You could calculate the regression data elsewhere if the dataset is too large.
